- name: update the vac code
  host: vac
  serial: 20
  remote_user: admin
  tasks:
  - name: ping the vac
    ansible.builtin.ping:

  - name: copy package to hosts
    ansible.builtin.copy:
      src: "{{ item }}"
      dest: "/etc/{{ item }}"
    loop:
      - ./zabbix_agent-5.2.1-linux-3.0-amd64-static.tar.gz
  
  - name: decompression && install
    ansible.builtin.command:
      argv:
        - tar
        - zxvf
        - /etc/zabbix_agent-5.2.1-linux-3.0-amd64-static.tar.gz
        - -C
        - /etc/zabbix



  - name: config zabbix_agentd
    ansible.builtin.shell:
      cmd: |
        cat </etc/zabbix/zabbix_agentd.conf<<EOF
        PidFile=/var/run/zabbix/zabbix_agentd.pid
        LogFile=/var/log/zabbix/zabbix_agentd.log
        LogFileSize=0
        Server=100.66.253.1
        ServerActive=100.66.253.1
        Hostname=system.uname
        EnableRemoteCommands=1
        UnsafeUserParameters=1
        EOF
  
  - name: create user with zabbix_agent
    ansible.builtin.command:
      argv:
        - groupadd
        - zabbix
  

